### ISSUE TITLE
Building and running locally

### ISSUE THREAD

**Issue by Alberto247** [thefifthmatt/windmill-client#43]
Did someone manage to build and run this locally? It seems that proto.sh can't find SoyToJsSrcCompiler.jar.
I tried downloading it from the google closure template page, but it says that not all code is in Soy V2, and it refuses to compile it.
If someone did, can i know your system configuration?
Thanks

**Comment by hbi99** [comment]
I have...though I extracted gameplay parts and abandoned Angular approach completely. Additionally, I implemented the game as application in my platform, called Karaqu. Below is a youtube clip...**the code is open source**

https://youtu.be/-Nd7oOHxaCE?si=oEEJ7El0wG2Wba6c
